version: '3.4'
services:
  gaia:
    image: gaia
    build:
      context: ./gaia
      args:
        - GROUP_ID=1000
        - USER_ID=1000
    command: gaiad start --rpc.laddr tcp://0.0.0.0:26657
    volumes:
      - ./data:/home/gaia/
    ports:
      - 26657:26657
  lcd:
    image: gaia
    command: gaiacli rest-server --laddr tcp://0.0.0.0:1317 --node http://gaia:26657 --chain-id wormhole --trust-node
    restart: always
    ports:
      - 1317:1317
  qt:
    image: quantum-tunnel
    build:
      context: ./quantum-tunnel
    command: sh -c "sleep 10; quantum-tunnel -c /data/config.json start"
    restart: always
    volumes:
      - ./data:/data
    environment:
      - COSMOS_SIGNER_SEED=crush carbon concert spirit energy stumble pioneer rescue region benefit coral dragon delay edit emotion judge image other reunion decade area easily ability snake
      - SUBSTRATE_SIGNER_SEED=flat reflect table identify forward west boat furnace similar million list wood
  wormhole:
    image: wormhole
    build:
      context: ./wormhole
    command: wormhole --dev --unsafe-rpc-external --unsafe-ws-external
    ports:
      - 9933:9933
      - 9944:9944
