version: '3.4'
services:
  gaia:
    image: gaia
    build:
      context: ./gaia
      args:
        - GROUP_ID=1000
        - USER_ID=1000
    command: gaiad start --home "/home/gaia/.gaiad"  --rpc.laddr tcp://0.0.0.0:26657
    volumes:
      - ./data:/home/gaia/
    ports:
      - 26657:26657
  lcd:
    image: gaia
    command: sh -c "sleep 10; gaiacli tx ibc wasm store "/wasm/substrate_client.wasm"  --gas=2000000 --home "/home/gaia/.gaiacli" --node http://gaia:26657 --chain-id wormhole --from=relayer --keyring-backend test --yes; gaiacli rest-server --laddr tcp://0.0.0.0:1317 --node http://gaia:26657 --home "/home/gaia/.gaiacli"  --chain-id wormhole --trust-node"
    volumes:
      - ./data:/home/gaia
    ports:
      - 1317:1317
  qt:
    image: quantum-tunnel
    build:
      context: ./quantum-tunnel
    command: sh -c "sleep 20; quantum-tunnel -c /data/config.json start"
    restart: always
    volumes:
      - ./data:/data
    environment:
      - COSMOS_SIGNER_SEED=sunny source soul allow brave luggage mandate metal worth state vapor couple butter retreat solid drift cargo alley degree junk bean price element easy
      - SUBSTRATE_SIGNER_SEED=flat reflect table identify forward west boat furnace similar million list wood
  wormhole:
    image: wormhole
    build:
      context: ./wormhole
    command: wormhole --dev --unsafe-rpc-external --unsafe-ws-external
    ports:
      - 9933:9933
      - 9944:9944
